## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [1]:
import numpy as np

In [10]:
x = np.arange(5,10)
y = np.arange(15,20)
# print(x)

[5 6 7 8 9]


In [61]:
# Non-numpy way to compute the outer product
outer_product = []
assert(len(x)==len(y)),'Dimension not match!'

for i in range(len(x)):
    row = []
    for j in range(len(y)):
        row.append(x[i]*y[j])
    outer_product.append(row)

print('Outer product of lists x and y is: ', outer_product)


Outer product of lists x and y is:  [[75, 80, 85, 90, 95], [90, 96, 102, 108, 114], [105, 112, 119, 126, 133], [120, 128, 136, 144, 152], [135, 144, 153, 162, 171]]


In [52]:
# Non-numpy way to compute the trace of the result

row = []
for i in range(len(x)):
    row.append(outer_product[i][i])
# print(row)
trace = sum(row)
print('The trace of the outer product matrics is: ', trace)


The trace of the outer product matrics is:  605


In [59]:
# Numpy way to compute the outer product
np_outer = np.outer(x,y)
print('Outer product of lists x and y is: ', np_outer)

Outer product of lists x and y is:  [[ 75  80  85  90  95]
 [ 90  96 102 108 114]
 [105 112 119 126 133]
 [120 128 136 144 152]
 [135 144 153 162 171]]


In [58]:
# Numpy way to compute the trace of the result
n_trace = np.trace(outer_p)
print('The trace of the outer product matrics is: ', n_trace)

The trace of the outer product matrics is:  605


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [ ]:
A = np.random.randn(12)
B = np.random.randn(12)
A = A.reshape(4,3)
B = B.reshape(3,4)
print(A)
print(B)

In [ ]:
C = 